#!/usr/bin/env bash
#
# Build Magicpond and launch a local Paper test server with the plugin installed.
#
# Usage:
#   bash scripts/run-server.sh          # build the plugin, then start the server
#   mvn -Prun verify                    # same thing, driven from Maven / your IDE
#
# Everything lives in a gitignored ./run directory, so it's safe to delete to
# get a clean server. The Paper jar is cached there and only downloaded once.
#
# Configurable via environment variables:
#   PAPER_VERSION   Minecraft/Paper version to run        (default: 1.21.1)
#   RUN_DIR         Working directory for the test server  (default: run)
#   SKIP_BUILD      Set to "true" to skip `mvn package`    (default: false)
#   JAVA_OPTS       Extra JVM flags                        (default: -Xms1G -Xmx2G)
#   MVN             Maven executable                       (default: mvn)
#
set -euo pipefail

PAPER_VERSION="${PAPER_VERSION:-1.21.1}"
RUN_DIR="${RUN_DIR:-run}"
SKIP_BUILD="${SKIP_BUILD:-false}"
JAVA_OPTS="${JAVA_OPTS:--Xms1G -Xmx2G}"
MVN="${MVN:-mvn}"

# Resolve the project root (this script lives in <root>/scripts).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_DIR"

command -v curl >/dev/null 2>&1 || { echo "[run] ERROR: curl is required to download Paper." >&2; exit 1; }

# 1. Build the plugin (unless the caller already did).
if [ "$SKIP_BUILD" != "true" ]; then
  echo "[run] Building plugin with $MVN ..."
  "$MVN" -q -DskipTests package
fi

# Locate the built plugin jar (skip the shade plugin's original-/sources/javadoc jars).
PLUGIN_JAR="$(ls -t target/*.jar 2>/dev/null | grep -Ev 'original-|-sources|-javadoc' | head -n1 || true)"
if [ -z "$PLUGIN_JAR" ]; then
  echo "[run] ERROR: no plugin jar found in target/. Did the build succeed?" >&2
  exit 1
fi

mkdir -p "$RUN_DIR/plugins"

# 2. Download Paper for the requested version if it isn't cached yet.
PAPER_JAR="$RUN_DIR/paper-$PAPER_VERSION.jar"
if [ ! -f "$PAPER_JAR" ]; then
  echo "[run] Resolving latest Paper build for $PAPER_VERSION ..."
  BUILDS_JSON="$(curl -fsSL "https://api.papermc.io/v2/projects/paper/versions/$PAPER_VERSION/builds")"
  BUILD="$(printf '%s' "$BUILDS_JSON" | grep -o '"build":[0-9]*' | grep -o '[0-9]*' | tail -n1)"
  if [ -z "${BUILD:-}" ]; then
    echo "[run] ERROR: could not determine a Paper build for $PAPER_VERSION." >&2
    echo "[run] Check that the version exists at https://papermc.io/downloads/paper" >&2
    exit 1
  fi
  JAR_NAME="paper-$PAPER_VERSION-$BUILD.jar"
  URL="https://api.papermc.io/v2/projects/paper/versions/$PAPER_VERSION/builds/$BUILD/downloads/$JAR_NAME"
  echo "[run] Downloading Paper $PAPER_VERSION build $BUILD ..."
  curl -fsSL -o "$PAPER_JAR" "$URL"
fi

# 3. Install the freshly built plugin (replacing any older copy) and accept the EULA.
echo "[run] Installing $(basename "$PLUGIN_JAR") into $RUN_DIR/plugins/"
rm -f "$RUN_DIR"/plugins/[Mm]agicpond-*.jar
cp "$PLUGIN_JAR" "$RUN_DIR/plugins/"
echo "eula=true" > "$RUN_DIR/eula.txt"

# Frictionless defaults for local testing (only written once; edit freely afterward).
if [ ! -f "$RUN_DIR/server.properties" ]; then
  cat > "$RUN_DIR/server.properties" <<EOF
# Generated by scripts/run-server.sh for local plugin testing.
online-mode=false
motd=Magicpond dev server
max-players=5
spawn-protection=0
EOF
fi

# 4. Launch (interactive console: type 'stop' or press Ctrl+C to quit).
echo "[run] Starting Paper $PAPER_VERSION ..."
cd "$RUN_DIR"
exec java $JAVA_OPTS -jar "paper-$PAPER_VERSION.jar" nogui
